#### **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [6]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [8]:
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [26]:
# Возможно только четыре

In [15]:
# Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [16]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [17]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [19]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
# возможно только четыре

In [24]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
b = a.reshape(12, -1)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [25]:
np.linalg.matrix_rank(b)

1

In [29]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой 
# из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [48]:
c = np.random.randn(3, 4)
c

array([[-0.71061307, -0.99667159, -0.6136683 ,  1.0511582 ],
       [-0.55091757,  0.25495907,  1.44724706, -1.13996101],
       [ 0.23651274,  0.29137634,  0.7409626 , -0.19780828]])

In [49]:
c.mean()

-0.015618649864168575

In [50]:
c.std()

0.7889054550138099

In [46]:
c.size

12

In [43]:
c = c.flatten()
c

array([ 1.16140544, -0.4973349 ,  1.56972735,  0.38598509,  2.50223094,
        0.77030764,  1.81059259, -1.44593434, -0.91997082,  0.43891429,
        0.1388627 , -0.13890899])

In [47]:
c.size

12

In [76]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
b = np.arange(0, 22, 2)
a = b[:0:-1]
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [79]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, 
# убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a и b?
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [80]:
a.shape

(10,)

In [81]:
b.shape

(1, 10)

In [85]:
# Вертикально соединить массивы a и b. 
# a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. 
#Итоговый массив v должен иметь атрибут size, равный 10.

In [89]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [90]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [92]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [93]:
v.size

10

In [94]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
# состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? 
# Получится ли вычислить обратную матрицу для матрицы B и почему?

In [97]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [120]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [102]:
B.size

16

In [121]:
B_inv = np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [111]:
# Не получается инвертировать матрицу, хотя матрица и имеет размер 4 * 4.
# Почему не знаю.

In [115]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)
np.random.randint(0, 10, 3)

array([6, 3, 7])

In [118]:
# Создайте одномерный массив c, составленный из последовательности 
# 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.
c = np.random.randint(0, 16, 16)
c

array([ 1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12, 11,  8])

In [119]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
C = c.reshape(4, 4)
C

array([[ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9],
       [ 5, 12, 11,  8]])

In [122]:
D = C * 10 + B
D

array([[ 15,  84, 133, 162],
       [ 64,  60, 236, 232],
       [ 63,  86, 259, 302],
       [ 82, 242, 322, 382]])

In [123]:
np.linalg.det(D)

-26039199.999999955

In [124]:
np.linalg.matrix_rank(D)

4

In [135]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.05682356, -0.00670451,  0.01558727,  0.01584688],
       [ 0.00200774,  0.00138176, -0.01099112,  0.00699868],
       [ 0.02426956,  0.03005392, -0.02911149, -0.00553012],
       [-0.00953178, -0.02476958,  0.02815601, -0.00055608]])

In [140]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - 
# в качестве источников данных, получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых 
# соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

D_inv = np.where((0 < D_inv)&(D_inv > 0), 1, 0)

In [141]:
D_inv

array([[0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

In [143]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [144]:
C

array([[ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9],
       [ 5, 12, 11,  8]])

In [145]:
E = np.where([D_inv == 1], B, C)
E

array([[[  1,   7,  23,  32],
        [ 14,  50,  15, 122],
        [ 23,  86,  11,   9],
        [  5,  12, 212,   8]]])